name: SBOM

on: workflow_dispatch

jobs:
  build:
    name: 'Build'
    runs-on: ubuntu-latest

    steps:
     - name: build
       run: echo "Building.."
        
  change:
    # type of machine to run the job on
    needs: build
    runs-on: ubuntu-latest
    name: 'ServiceNow DevOps Change'
    steps:
      - name: ServiceNow Change
        uses: ServiceNow/servicenow-devops-change@dev
        with:
          devops-integration-token: ${{ secrets.SN_DEVOPS_INTEGRATION_TOKEN }}
          instance-url: ${{ secrets.SN_INSTANCE_URL }}
          tool-id: ${{ secrets.SN_ORCHESTRATION_TOOL_ID }}
          context-github: ${{ toJSON(github) }}
          job-name: 'ServiceNow DevOps Change'
          change-request: '{"attributes":{"chg_model":{"name":"DevOps"},"priority": "2","comments": "This is a sample pipeline script to be added in your change step","work_notes": "Update this to work_notes", "u_response_to_ques_1":"no"}}'
  
    
  
