name: SBOM

on: workflow_dispatch
  # push:
  #   branches: [ "main" ]
  # pull_request:
  #   branches: [ "main" ]
  #   types: [opened, synchronize, reopened]

jobs:
  build:
    name: 'Build'
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven Repo1
      run: |
        cd RepoOne
        mvn clean install
        cd ..
    - name: Build with Maven Repo2
      run: |
        cd RepoTwo
        mvn clean install
        cd ..
    - uses: actions/upload-artifact@master
      with:
        name: RepoOneArtifact
        path: RepoOne/target
    - uses: actions/upload-artifact@master
      with:
        name: RepoTwoArtifact
        path: RepoTwo/target
    
  sbom_out_repo_one:
    name: 'sbom_out_repo_one'
    needs: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/download-artifact@master
      with:
        name: RepoOneArtifact
        path: RepoOne/target
    - name: Output SBOM
      run: |
        echo "*************************"
        ls RepoOne/target/bom.json

  sbom_out_repo_two:
    name: 'sbom_out_repo_two'
    needs: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/download-artifact@master
      with:
        name: RepoTwoArtifact
        path: RepoTwo/target
    - name: Output SBOM
      run: |
        echo "*************************"
        ls RepoTwo/target/bom.json
        curl "https://empasarkarv5.service-now.com/api/sbom/core/upload" \
          --request POST \
          --header "Accept:application/json" \
          --user 'admin':'Test@123' \
          --d RepoTwo/target/bom.json
  
    
  
