name: SBOM upload

on: 
  # push:
  #   branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    types: [opened, synchronize, reopened]

jobs:
  build:
    name: 'Build'
    runs-on: ubuntu-latest

    steps:
      - name: test
        run: echo "hello"
    


  
    
  
